trigger:
- master

jobs:
  - job: RunAskUI
    continueOnError: false
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'
      - bash: |
          sudo ufw disable
          echo 'Start UIController'
          docker run -d -p 6769:6769 --cidfile container.cid askuigmbh/askui-ui-controller:0.11.2-chrome-129.0-amd64
          echo 'Run npm install'
          npm install
          echo 'Run AskUI'
          export ASKUI_TOKEN=$(ASKUI_TOKEN)
          export ASKUI_WORKSPACE_ID=$(ASKUI_WORKSPACE_ID)
          npm run askui
        continueOnError: true
        displayName: 'Run AskUI'
      - bash: |
          curl -o allure-commandline-2.10.0.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.10.0/allure-commandline-2.10.0.tgz
          sudo tar -zxf allure-commandline-2.10.0.tgz -C .
          echo "Creating allure-report"
          ./allure-2.10.0/bin/allure generate allure-results -o allure-report
          echo "allure-report created"
      # Install https://github.com/mclay/azure-pipeline-allure-report first
      - task: PublishAllureReport@1
        displayName: 'Publish Allure Report'
        inputs:
          reportDir: 'allure-report'
